KotoLogProject/KotoLogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from .views import PortfolioView,SearchFormView
from journals.views import HomeView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PortfolioView.as_view(), name="portfolio"),
    path('home/', HomeView.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('journals/', include('journals.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

KotoLogProject/accounts/urls.py
from django.urls import path
from .views import (SignupView, LoginView, LogoutView, UserEditView,UserPageView ,
    CustomPasswordChangeView, CustomPasswordChangeDoneView,
    InvitationUrlView,FamilyDeleteView,ChildDeleteView)

app_name='accounts'
urlpatterns = [
    path('signup/', SignupView.as_view(), name="signup"),
    path('signup/<uuid:uuid>/', SignupView.as_view(), name='signup_with_invite'),
    path('login/', LoginView.as_view(), name="login"),
    path('login/<uuid:uuid>/', LoginView.as_view(), name='login_with_invite'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("user_edit/", UserEditView.as_view(), name="user_edit"),
    path("user_page/", UserPageView.as_view(), name="user_page"),
    path("password_change/", CustomPasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", CustomPasswordChangeDoneView.as_view(), name="password_change_done"),
    path("invitation_url/", InvitationUrlView.as_view(), name="invitation_url"),
    path('family/delete/', FamilyDeleteView.as_view(), name='family_delete'),
    path('child/delete/<int:child_id>/', ChildDeleteView.as_view(), name='child_delete'),
]

KotoLogProject/journals/urls.py
from django.urls import path
from .views import (
    ChildcareJournalListView,CreateChildcareJournalView, 
    ChildcareJournalDetailView,EditChildcareJournalView,
    DeleteChildcareJournalsView)

app_name='journals'
urlpatterns = [
    path("childcare_journal_list/", ChildcareJournalListView.as_view(), name="childcare_journal_list"),
    path('create_childcare_journal/', CreateChildcareJournalView.as_view(), name='create_childcare_journal'),
    path('journal_detail/<int:journal_id>/', ChildcareJournalDetailView.as_view(), name='journal_detail'),
    path('edit_childcare_journal/<int:journal_id>/', EditChildcareJournalView.as_view(), name='edit_childcare_journal'), 
    path('delete_childcare_journals/', DeleteChildcareJournalsView.as_view(), name='delete_childcare_journals'),
]

KotoLogProject/common/models.py
from django.db import models

# Create your models here.

KotoLogProject/KotoLogProject/forms.py
from django import forms
from accounts.models import Child

class SearchJournalForm(forms.Form):
    search_query = forms.CharField(
        required=False, 
        label="", 
        widget=forms.TextInput(attrs={'placeholder': 'キーワード', 'class': 'form-control'})
    )
    
    filter_option = forms.ChoiceField(
        required=False, 
        label="",
        widget=forms.Select(attrs={'class': 'form-select'}),
        choices=[]  # choicesは__init__で動的に設定
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        data = kwargs.get('data', None)  # データを取得
        super(SearchJournalForm, self).__init__(*args, **kwargs)

        # デフォルトのフィルタ選択肢
        filter_choices = [
            ('public', '公開'),
        ]

        # ログイン済みユーザーには追加の選択肢を表示
        if user and user.is_authenticated:
            filter_choices = [
                ('', '公開 + 家族'),
                ('public', '公開'),
                ('family', '家族'),
            ]

            # 子どもごとのフィルタも追加
            children = Child.objects.filter(family=user.family)
            for child in children:
                filter_choices.append((f"child_{child.id}", f"{child.child_name}の記録"))
            
            filter_choices.append(('favorites', 'お気に入り'))

        # フィルタ選択肢を設定
        self.fields['filter_option'].choices = filter_choices

        # 未ログイン時は選択不可
        if not user or not user.is_authenticated:
            self.fields['filter_option'].widget.attrs['disabled'] = 'disabled'

        # デフォルトの値をフォームに再設定
        if data:
            self.fields['search_query'].initial = data.get('search_query', '')
            self.fields['filter_option'].initial = data.get('filter_option', '')

KotoLogProject/common/views.py
from django.shortcuts import render

# Create your views here.

KotoLogProject/templates/common/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    {% load static %}
    <link rel="stylesheet" href="{% static "css/reset.css" %}">    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>
    <title>KotoLog</title>
</head>
<body>
    <header class="navbar navbar-expand-md sticky-top p-2">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static "img/kotolog.png" %}" alt="KotoLog" width="120px">
        </a>
        <!-- 検索フォーム -->
        <div class="d-none d-md-flex mx-auto">
            <form method="GET" action="{% url 'journals:childcare_journal_list' %}" class="d-flex search-form">
                {{ search_form.search_query }}
                {{ search_form.filter_option }}
                <button type="submit" class="btn search-btn">
                    <img src="{% static "img/search.png" %}" alt="検索" width="20px">
                </button>
            </form>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- ハンバーガーメニュー内のコンテンツ -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto align-items-center">
                <!-- モバイル時の検索フォーム -->
                <li class="nav-item d-md-none">
                    <form method="GET" action="{% url 'journals:childcare_journal_list' %}" class="d-flex search-form">
                        {{ search_form.search_query }}
                        {{ search_form.filter_option }}
                        <button type="submit" class="btn search-btn">
                            <img src="{% static "img/search.png" %}" alt="検索" width="20px">
                        </button>
                    </form>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'journals:create_childcare_journal' %}" title="育児記録作成">
                        <img src="{% static "img/edit.png" %}" alt="育児記録作成" width="36px">
                        <span class="d-md-none">育児記録作成</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'journals:childcare_journal_list' %}?favorites=true" title"お気に入り">
                        <img src="{% static "img/favorite.png" %}" alt="お気に入り" width="24px">
                        <span class="d-md-none">お気に入り</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:user_page' %}" title="アカウント情報">
                        <img src="{% static "img/kkrn_icon_user_5.png" %}" alt="アカウント情報" width="36px">
                        <span class="d-md-none">アカウント情報</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:logout' %}">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="btn btn-outline-success" href="{% url 'accounts:login' %}">ログイン</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </header>

    {% block content %}{% endblock %}
<script>
$(document).ready(function() {
    $('.search-btn').on('click', function(e) {
        let searchQuery = $('#id_search_query').val();
        let filterOption = $('#id_filter_option').val();
    
            if (searchQuery === '' && filterOption === '') {

                alert('検索キーワードまたはフィルターオプションのいずれかを入力してください。');
                return false;
            }
    });
});
</script>
</body>
</html>

KotoLogProject/templates/common/home.html
{% extends 'common/base.html' %}
{% block content %}
<section id="home"  class="m-3">
    {% if messages %}
      <div class="alert alert-success">
          {% for message in messages %}
              <p>{{ message }}</p>
          {% endfor %}
      </div>      
    {% endif %}
    
    <section class="mb-4">
        <h2 class="journal_title">最近のKotoLog
            <a href="{% url 'journals:childcare_journal_list' %}?segment=public" class="link-opacity-75-hover fs-6">すべて見る</a>
        </h2>       
        <!-- 最近のKotoLog カルーセル -->
        <div id="recentCarousel" class="carousel-container">
            <button class="carousel-prev" data-target="#recentCarousel">＜</button>
            <div class="carousel-track-container">
                <div class="carousel-track">
                    {% for journal in public_journals %}
                        {% include 'journals/childcare_journal_card.html' %}
                    {% empty %}
                    <p>最近の育児記録はありません。</p>
                    {% endfor %}
                </div>
            </div>
            <button class="carousel-next" data-target="#recentCarousel">＞</button>
        </div>
    </section>

    <section class="mb-4">
        <h2 class="journal_title">よく見られているKotoLog</h2>
        <div id="popularCarousel" class="carousel-container">
            <button class="carousel-prev" data-target="#popularCarousel">＜</button>
            <div class="carousel-track-container">
                <div class="carousel-track">
                    {% for journal in popular_journals %}
                        {% include 'journals/childcare_journal_card.html' %}
                    {% empty %}
                    <p>よく見られている育児記録はありません。</p>                        
                    {% endfor %}
                </div>
            </div>
            <button class="carousel-next" data-target="#popularCarousel">＞</button>
        </div>
    </section>    

    {% if user.is_authenticated %}
        {% if request.user.family %}
        <section class="mb-4">
            <h2 class="journal_title">家族のKotoLog
                <a href="{% url 'journals:childcare_journal_list' %}?segment=family" class="link-opacity-75-hover fs-6">すべて見る</a>
            </h2>
            <div id="familyCarousel" class="carousel-container">
                <button class="carousel-prev" data-target="#familyCarousel">＜</button>
                <div class="carousel-track-container">
                    <div class="carousel-track">
                        {% for journal in family_journals %}
                            {% include 'journals/childcare_journal_card.html' %}
                        {% empty %}
                        <p>家族の育児記録はありません。</p>                        
                        {% endfor %}
                    </div>
                </div>
                <button class="carousel-next" data-target="#familyCarousel">＞</button>
            </div>
        </section>     

        {% for child_id, journals in child_journals.items %}
            {% if journals %}
            <section class="mb-4">
                <h2 class="journal_title">{{ journals.0.child.child_name }}のKotoLog
                    <a href="{% url 'journals:childcare_journal_list' %}?segment=child&child_id={{ child_id }}" class="link-opacity-75-hover fs-6">すべて見る</a>
                </h2>
                <div id="kidCarousel{{ child_id }}" class="carousel-container">
                    <button class="carousel-prev" data-target="#kidCarousel{{ child_id }}">＜</button>
                    <div class="carousel-track-container">
                        <div class="carousel-track">
                            {% for journal in journals %}
                                {% include 'journals/childcare_journal_card.html' %}
                            {% empty %}
                            <p>{{ journals.0.child.child_name }}の育児記録はありません。</p>                                
                            {% endfor %}
                        </div>
                    </div>
                    <button class="carousel-next" data-target="#kidCarousel{{ child_id }}">＞</button>
                </div>
            </section>  
            {% endif %}
        {% endfor %}   
        {% endif %}
    <section class="mb-4">
        <h2 class="journal_title">お気に入りのKotoLog
            <a href="{% url 'journals:childcare_journal_list' %}?favorites=true" class="link-opacity-75-hover fs-6">すべて見る</a>
        </h2>        
        <div id="favoriteCarousel" class="carousel-container">
            <button class="carousel-prev" data-target="#favoriteCarousel">＜</button>
            <div class="carousel-track-container">
                <div class="carousel-track">
                    {% for journal in favorite_journals %}
                        {% include 'journals/childcare_journal_card.html' %}
                    {% empty %}
                    <p>お気に入りの育児記録はありません。</p>                        
                    {% endfor %}
                </div>
            </div>
            <button class="carousel-next" data-target="#favoriteCarousel">＞</button>
        </div>
    </section>    
    {% endif %}
</section>

<!-- モーダルテンプレートの読み込み -->
{% include 'journals/journal_detail.html' %}
{% load static %}
<script src="{% static 'js/function.js' %}"></script>     
{% endblock %}