KotoLogProject/KotoLogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from .views import PortfolioView,SearchFormView
from journals.views import HomeView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PortfolioView.as_view(), name="portfolio"),
    path('home/', HomeView.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('journals/', include('journals.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

KotoLogProject/accounts/urls.py
from django.urls import path
from .views import (SignupView, LoginView, LogoutView, UserEditView,UserPageView ,
    CustomPasswordChangeView, CustomPasswordChangeDoneView,
    InvitationUrlView,FamilyDeleteView,ChildDeleteView)

app_name='accounts'
urlpatterns = [
    path('signup/', SignupView.as_view(), name="signup"),
    path('signup/<uuid:uuid>/', SignupView.as_view(), name='signup_with_invite'),
    path('login/', LoginView.as_view(), name="login"),
    path('login/<uuid:uuid>/', LoginView.as_view(), name='login_with_invite'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("user_edit/", UserEditView.as_view(), name="user_edit"),
    path("user_page/", UserPageView.as_view(), name="user_page"),
    path("password_change/", CustomPasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", CustomPasswordChangeDoneView.as_view(), name="password_change_done"),
    path("invitation_url/", InvitationUrlView.as_view(), name="invitation_url"),
    path('family/delete/', FamilyDeleteView.as_view(), name='family_delete'),
    path('child/delete/<int:child_id>/', ChildDeleteView.as_view(), name='child_delete'),
]

KotoLogProject/journals/urls.py
from django.urls import path
from .views import (
    ChildcareJournalListView,CreateChildcareJournalView, 
    ChildcareJournalDetailView,EditChildcareJournalView,
    DeleteChildcareJournalsView)

app_name='journals'
urlpatterns = [
    path("childcare_journal_list/", ChildcareJournalListView.as_view(), name="childcare_journal_list"),
    path('create_childcare_journal/', CreateChildcareJournalView.as_view(), name='create_childcare_journal'),
    path('journal_detail/<int:journal_id>/', ChildcareJournalDetailView.as_view(), name='journal_detail'),
    path('edit_childcare_journal/<int:journal_id>/', EditChildcareJournalView.as_view(), name='edit_childcare_journal'), 
    path('delete_childcare_journals/', DeleteChildcareJournalsView.as_view(), name='delete_childcare_journals'),
]

KotoLogProject/journals/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import User,Child

class ChildcareJournal(models.Model):
    child = models.ForeignKey(Child, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    published_on = models.DateField()
    title = models.CharField(max_length=255)
    content = models.TextField()
    is_public = models.BooleanField(default=False)
    impression_count = models.PositiveIntegerField(default=0) 
    image_url = models.FileField(upload_to='uploads/', null=True, blank=True) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "childcare_journals"

class Hashtag(models.Model):
    hashtag_word = models.CharField(max_length=255, unique=True)  
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "hashtags"

class ChildcareJournalHashtag(models.Model):
    childcare_journal = models.ForeignKey(ChildcareJournal, on_delete=models.CASCADE)
    hashtag = models.ForeignKey(Hashtag, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "childcare_journals_hashtags"

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    childcare_journal = models.ForeignKey(ChildcareJournal, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "favorites"

class ChildcareJournalAccessLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    childcare_journal = models.ForeignKey(ChildcareJournal, on_delete=models.CASCADE)
    accessed_at = models.DateTimeField() 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "childcare_journals_access_logs"

KotoLogProject/journals/forms.py
from django import forms
from .models import ChildcareJournal
from accounts.models import Child
from django.utils import timezone

class ChildcareJournalForm(forms.ModelForm):
    
    class Meta:
        model = ChildcareJournal
        fields = ['child', 'title', 'published_on', 'content', 'is_public', 'image_url']
        
        labels = {
            'child': '子供選択',
            'title': 'タイトル',
            'published_on': 'いつの出来事？',
            'content': '何が起こった？',
            'is_public': '公開する',
            'image_url': '画像または動画を選択',
        }

        widgets = {
            'child': forms.Select(attrs={'class': 'form-select', 'placeholder': '子供を選択してください'}),
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'タイトル'}),
            'published_on': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date',
                'value': timezone.now().date(),
                'placeholder': '公開日を選択してください'
            }),
            'is_public': forms.CheckboxInput(attrs={'class': 'form-check-label'}),
            'image_url': forms.FileInput(attrs={'class': 'form-control'}),
        }
    # contentフィールドに最大文字数制限を追加
    content = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': '反応、対応策を簡単に記録してください。例: ○○が原因で癇癪を起こしたので、お気に入りのおもちゃで気を紛らわせました。#対応策 #癇癪',
            'maxlength': '2000'
        }),
        max_length=2000,  # 最大2000文字に設定
        label="何が起こった？"
    )        
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ChildcareJournalForm, self).__init__(*args, **kwargs)
        
        # Filter child choices to those related to the user's family
        if user:
            self.fields['child'].queryset = Child.objects.filter(family=user.family)

        self.fields['is_public'].initial = False  # Default to not public
        self.fields['published_on'].initial = timezone.now().date()

KotoLogProject/journals/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.views import View
from .forms import ChildcareJournalForm
from .models import (
    ChildcareJournal, Hashtag, 
    ChildcareJournalHashtag, Favorite,
    ChildcareJournalAccessLog)
from accounts.models import User,Child
from KotoLogProject.forms import SearchJournalForm
from django.db.models import Prefetch, Count, Case, When, Value, BooleanField,Q
from django.utils import timezone
from django.contrib import messages
from django.core.validators import FileExtensionValidator
from django.conf import settings
from django.urls import reverse
from django.http import HttpResponseRedirect
import re
import hashlib
import subprocess
import os
import uuid

# アップロードファイルサイズ
MAX_FILE_SIZE_MB = 10  # 10MBに設定

## 共通関数 ##
# 上位n件を取得
def get_top_n(queryset, n=10):
    return queryset[:n]

# お気に入りフラグを取得
def get_favorite_flagged_queryset(queryset, user):
    return queryset.annotate(
        is_favorited=Case(
            When(favorite__user=user, then=Value(True)),
            default=Value(False),
            output_field=BooleanField()
        )
    ).select_related('child')

## 動画ファイルをMP4形式に変換する関数 ##
def convert_video_to_mp4(file_path):
    # 対象の拡張子を定義（webm, ogg, mov など）
    valid_video_extensions = ('.mov', '.webm', '.ogg')

    if file_path.lower().endswith(valid_video_extensions):
        try:
            # 出力ファイル名を変更してMP4にする（ユニークな名前を生成）
            base_name = os.path.splitext(file_path)[0]
            unique_mp4_file_path = f"{base_name}_{uuid.uuid4().hex}.mp4"
            
            # ffmpegを使用してMOVをMP4に変換
            command = f'ffmpeg -i "{file_path}" -vcodec h264 -acodec aac "{unique_mp4_file_path}"'
            subprocess.run(command, shell=True, check=True)
            
            # 変換後、元のMOVファイルを削除
            os.remove(file_path)
            
            return unique_mp4_file_path  # 成功した場合、新しいMP4ファイルのパスを返す
        except subprocess.CalledProcessError:
            return None  # 変換に失敗した場合
    return file_path  # MOV以外の形式はそのまま返す


class CreateChildcareJournalView(View):
    def get(self, request):
        children = Child.objects.filter(family=request.user.family)
        if not children.exists():
            messages.error(request, '育児記録の作成前に子ども情報を登録してください。')
            return redirect('accounts:user_page')
        
        form = ChildcareJournalForm(user=request.user)
        return render(request, 'journals/create_childcare_journal.html', {'form': form})

    def post(self, request):
        form = ChildcareJournalForm(request.POST, request.FILES)

        # ファイルチェック
        uploaded_file = request.FILES.get('image_url')
        if uploaded_file:
            if uploaded_file.size > MAX_FILE_SIZE_MB * 1024 * 1024:
                messages.error(request, f"ファイルサイズは{MAX_FILE_SIZE_MB}MB以下にしてください。")
                return render(request, 'journals/create_childcare_journal.html', {'form': form})
            
            # 許可するファイル拡張子（画像および動画ファイル形式）
            allowed_extensions = ['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov','.webm', '.ogg']
            file_extension = uploaded_file.name.split('.')[-1].lower()
            if file_extension not in allowed_extensions:
                messages.error(request, "対応しているファイル形式は .jpg, .jpeg, .png, .gif, .mp4, .mov, .webm, .ogg です。")
                return render(request, 'journals/create_childcare_journal.html', {'form': form})

            # ファイルの保存先を設定
            file_path = os.path.join(settings.MEDIA_ROOT, 'uploads', uploaded_file.name)
            with open(file_path, 'wb') as f:
                for chunk in uploaded_file.chunks():
                    f.write(chunk)
            
            # 動画ファイルの変換（MOVの場合）
            converted_file_path = convert_video_to_mp4(file_path)
            if converted_file_path is None:
                messages.error(request, "動画の変換に失敗しました。再度お試しください。")
                return render(request, 'journals/create_childcare_journal.html', {'form': form})

            # 変換後のファイルパスをフォームに渡す
            uploaded_file.name = os.path.basename(converted_file_path)

        if form.is_valid():
            # フォームから育児記録を保存
            childcare_journal = form.save(commit=False)
            childcare_journal.user = request.user # 現在のユーザーを設定
            childcare_journal.save()
            # 本文からハッシュタグを抽出
            content = form.cleaned_data['content']
            hashtags = re.findall(r'#(\w+)', content)

            for hashtag_word in hashtags:
                # ハッシュタグをデータベースに保存（存在しない場合は新規作成）
                hashtag, created = Hashtag.objects.get_or_create(hashtag_word=hashtag_word)
                # ChildcareJournalHashtagモデルに関連付け
                ChildcareJournalHashtag.objects.get_or_create(
                    childcare_journal=childcare_journal,
                    hashtag=hashtag
                )
            # ホームページにリダイレクト
            return redirect('home')

        # バリデーションエラーが発生した場合は再度フォームを表示
        return render(request, 'journals/create_childcare_journal.html', {'form': form})


class EditChildcareJournalView(View):
    def get(self, request, journal_id):
        journal = get_object_or_404(ChildcareJournal, id=journal_id)
        form = ChildcareJournalForm(instance=journal)
        return render(request, 'journals/edit_childcare_journal.html', {'form': form, 'journal': journal})

    def post(self, request, journal_id):
        journal = get_object_or_404(ChildcareJournal, id=journal_id)
        form = ChildcareJournalForm(request.POST, request.FILES, instance=journal)

        if form.is_valid():
            delete_image_flag = request.POST.get("delete_image") == "1"
            new_image = request.FILES.get("image_url")
            
            #  削除フラグが立っている または 現在の画像と新しい画像が異なる場合に削除処理
            if delete_image_flag or (new_image and journal.image_url != new_image):
                if journal.image_url:
                    journal.image_url.delete()
                    journal.image_url = None
                    
            # 新しい画像の登録処理
            if new_image:
                journal.image_url = new_image
            
                # ファイルサイズチェック
                if new_image.size > MAX_FILE_SIZE_MB * 1024 * 1024:
                    messages.error(request, f"ファイルサイズは{MAX_FILE_SIZE_MB}MB以下にしてください。")
                    return render(request, 'journals/edit_childcare_journal.html', {'form': form, 'journal': journal})
                
                allowed_extensions = ['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov','.webm', '.ogg']
                file_extension = new_image.name.split('.')[-1].lower()
                
                # ファイル形式チェック
                if file_extension not in allowed_extensions:
                    messages.error(request, "対応しているファイル形式は .jpg, .jpeg, .png, .gif, .mp4, .mov, .webm, .ogg です。")
                    return render(request, 'journals/edit_childcare_journal.html', {'form': form, 'journal': journal})

                # ファイルの保存先を設定
                file_path = os.path.join(settings.MEDIA_ROOT, 'uploads', new_image.name)
                with open(file_path, 'wb') as f:
                    for chunk in new_image.chunks():
                        f.write(chunk)

                # 動画ファイルの変換（MOVの場合）
                converted_file_path = convert_video_to_mp4(file_path)
                if converted_file_path is None:
                    messages.error(request, "動画の変換に失敗しました。再度お試しください。")
                    return render(request, 'journals/edit_childcare_journal.html', {'form': form, 'journal': journal})

                # 変換後のファイルパスをフォームに渡す
                new_image.name = os.path.basename(converted_file_path)                

            # すべての処理が完了したら保存
            journal.save()
            messages.success(request, "育児記録が更新されました。")
            return redirect('home')

        return render(request, 'journals/edit_childcare_journal.html', {'form': form, 'journal': journal})

class ChildcareJournalDetailView(View):
    
    def get(self, request, journal_id):  
        journal = get_object_or_404(ChildcareJournal, pk=journal_id)
        journal.impression_count += 1
        journal.save(update_fields=['impression_count']) 

        if request.user.is_authenticated:
            access_log = ChildcareJournalAccessLog(
                user=request.user,
                childcare_journal=journal,
                accessed_at=timezone.now()
            )
            access_log.save()
            
            data = {
                'title': journal.title,
                'content': journal.content,
                'published_on': journal.published_on.strftime('%Y/%m/%d'),
                'is_public': journal.is_public,
                'image_url': journal.image_url.url if journal.image_url else None,
                'is_owner': journal.user == request.user,
                'is_favorited': Favorite.objects.filter(user=request.user, childcare_journal=journal).exists(),
            }
        else:
            data = {
                'title': journal.title,
                'content': journal.content,
                'published_on': journal.published_on.strftime('%Y/%m/%d'),
                'is_public': journal.is_public,
                'image_url': journal.image_url.url if journal.image_url else None,
                'is_owner': journal.user == request.user,
                'is_favorited': "",
            }            
            
        return JsonResponse(data)

    def post(self, request, journal_id):
        journal = get_object_or_404(ChildcareJournal, id=journal_id)

        if 'add_to_favorites' in request.POST:
            if not Favorite.objects.filter(user=request.user, childcare_journal=journal).exists():
                Favorite.objects.create(user=request.user, childcare_journal=journal)
                return JsonResponse({'success': True, 'message': "育児記録をお気に入りに登録しました。", 'is_favorited': True})
            else:

KotoLogProject/templates/journals/childcare_journal_card.html
{% load custom_filters %}
<div class="carousel-item active">
    <div class="card h-100">
        <div class="card-body">
            <h6 class="card-subtitle d-flex justify-content-between mb-3">
                <span>
                {% if journal.child.family == request.user.family %}
                    <span style="background-color: {{ journal.child.id|generate_hsl_color }}"  class="child-name">{{ journal.child.child_name }}</span>
                {% endif %}
                {% if journal.is_favorited %}
                <span>★</span>
                {% endif %}
                </span>

            </h6>
             {% if journal.image_url %}
                {% if journal.image_url.url|is_video %}
                    <!-- 動画ファイルの場合は video タグを使用 -->
                    <video poster class="card-img-top" style="max-height: 200px; object-fit: cover;">
                        <source src="{{ journal.image_url.url }}" type="video/mp4">
                        お使いのブラウザは動画の再生をサポートしていません。
                    </video>
                {% else %}
                    <!-- 画像ファイルの場合は img タグを使用 -->
                    <img src="{{ journal.image_url.url }}" class="card-img-top" alt="Journal Image" style="max-height: 200px; object-fit: cover;">
                {% endif %}
            {% endif %}
            <h5 class="card-title mb-2 text-muted">{{ journal.title }}({{ journal.published_on|date:"Y/m/d"  }})</h5>
            <p class="card-text card-context">{{ journal.content|truncatewords:20 }}</p>
            <p class="card-text"><small class="text-muted">作成者: {{ journal.user.account_name }}</small></p>
        </div>
        <div class="card-footer">
            <button class="btn btn-primary w-100" data-id="{{ journal.id }}" data-bs-toggle="modal" data-bs-target="#journalModal">詳細を見る</button>
        </div>
    </div>
</div>

KotoLogProject/templates/journals/childcare_journal_list.html
{% extends 'common/base.html' %}
{% load custom_filters %}
{% block content %}
<section id="childcare_journal_list" class="m-3">
    {% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <form method="POST" action="{% url 'journals:delete_childcare_journals' %}?{{ request.GET.urlencode }}" onsubmit="return confirmDelete()">
        {% csrf_token %}
        {% if user.is_authenticated %}
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-danger mb-3 delete-button">選択した育児記録を削除</button>
        </div>
        {% endif %}
        {% if childcare_journals.exists %}
        <div class="cards row">
            {% for journal in childcare_journals %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h6 class="card-subtitle d-flex justify-content-between mb-3">
                            <span>
                            {% if journal.child.family == request.user.family %}
                               <span style="background-color: {{ journal.child.id|generate_hsl_color }}" class="child-name">{{ journal.child.child_name }}</span>
                            {% endif %}
                            {% if journal.is_favorited %}
                            <span>★</span>
                            {% endif %}
                            </span>                        
                        {% if journal.user_id == request.user.id %}
                        <input type="checkbox" name="selected_journals" value="{{ journal.id }}">
                        {% endif %}
                        </h6>
                        {% if journal.image_url %}
                            {% if journal.image_url.url|is_video %}
                                <!-- 動画ファイルの場合は video タグを使用 -->
                                <video poster class="card-img-top" style="max-height: 200px; object-fit: cover;">
                                    <source src="{{ journal.image_url.url }}" type="video/mp4">
                                    お使いのブラウザは動画の再生をサポートしていません。
                                </video>
                            {% else %}
                                <!-- 画像ファイルの場合は img タグを使用 -->
                                <img src="{{ journal.image_url.url }}" class="card-img-top" alt="Journal Image" style="max-height: 200px; object-fit: cover;">
                            {% endif %}
                        {% endif %}
                        <h5 class="card-title mb-2 text-muted">{{ journal.title }}</h5>
                        <p class="card-text card-context">{{ journal.content|truncatewords:20 }}</p>
                        <p class="card-text"><small class="text-muted">作成者: {{ journal.user.account_name }}</small></p>
                    </div>
                    <div class="card-footer">
                        <button type="button" class="btn btn-primary w-100" data-id="{{ journal.id }}" data-bs-toggle="modal" data-bs-target="#journalModal">詳細を見る</button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </form>

    {% else %}
    <p>育児記録が見つかりません。</p>
</section>

{% endif %}
{% include 'journals/journal_detail.html' %}

<script>
//削除ボタンの表示/非表示
$(document).ready(function() {
  // ページ読み込み時にチェックボックスの数をカウント
   if ($('input[type="checkbox"]').length == 0){
          $('.delete-button').hide();
   }
});

// 削除確認メッセージを表示する
function confirmDelete() {
    return confirm('チェックした育児記録を本当に削除しますか？');
}
</script>
{% endblock %}

KotoLogProject/templates/journals/create_childcare_journal.html
{% extends 'common/base.html' %}
{% load static %}
{% block content %}
<section id="create_childcare_journal" class="container mt-5 d-flex justify-content-center">
    <div class="col-md-8 col-lg-6">

        <form method="POST" action="" enctype="multipart/form-data" class="p-4 border rounded" id="journal_form">
            {% csrf_token %}

            <div class="form-group mb-3">
                {{ form.child.label_tag }}  <!-- 子供選択ラベル -->
                {{ form.child }}
            </div>

            <div class="form-group mb-3">
                {{ form.title.label_tag }}  <!-- タイトルラベル -->
                {{ form.title }}
            </div>

            <div class="form-group mb-3">
                {{ form.published_on.label_tag }}  <!-- 日付ラベル -->
                {{ form.published_on }}
            </div>

            <div class="form-group mb-3">
                {{ form.content.label_tag }}  <!-- 内容ラベル -->
                {{ form.content }}
                <div id="char-count">残り 2000 文字</div>
            </div>

            <div class="form-group mb-3">
                {{ form.is_public.label_tag }}  <!-- 公開設定ラベル -->
                {{ form.is_public }}
            </div>

            <div class="form-group mb-3">
                <label for="image_url">画像または動画を選択</label>
                <input type="file" name="image_url" id="image_url" class="form-control mt-2" onchange="previewMedia(event)">
                
                <!-- プレビューエリア -->
                <div id="image-preview" class="mt-3"></div>
            </div>

            {% if messages %}
            <div class="alert alert-success">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>      
            {% endif %}
            <button type="submit" class="btn btn-primary w-100">保存</button>
        </form>
    </div>
</section>
<script>
function confirmDelete() {
    if (confirm("本当にこの画像を削除しますか？")) {
        document.getElementById("delete_image").value = "1";
        document.getElementById("current-image").style.display = "none";
    }
}
document.addEventListener("DOMContentLoaded", function () {
    const form = document.getElementById("journal_form");

    const contentField = document.getElementById("id_content");  
    const charCountDisplay = document.getElementById("char-count");

    contentField.addEventListener("input", function() {
        const remaining = 2000 - contentField.value.length;
        charCountDisplay.textContent = `残り ${remaining} 文字`;
        if (remaining < 20) {
            charCountDisplay.style.color = "red";  // 文字数超過で赤色表示
        } else {
            charCountDisplay.style.color = "black";  // 通常色に戻す
        }
    });

    form.addEventListener("submit", function (event) {
        let errorMessage = "";
        const child = document.querySelector("select[name='child']").value;
        const title = document.querySelector("input[name='title']").value;
        const content = document.querySelector("textarea[name='content']").value;

        if (!child) {
            errorMessage += "子どもを選択してください。\n";
        }
        if (!title) {
            errorMessage += "タイトルを入力してください。\n";
        }
        if (!content) {
            errorMessage += "内容を入力してください。\n";
        }

        if (errorMessage) {
            alert(errorMessage);
            event.preventDefault(); // フォームの送信を停止
        }
    });
});

// 画像または動画のプレビュー表示
function previewMedia(event) {
    const file = event.target.files[0];
    const previewContainer = document.getElementById("image-preview");
    previewContainer.innerHTML = "";  // Clear existing preview

    if (file) {
        const fileType = file.type;
        if (fileType.startsWith("image/")) {
            const img = document.createElement("img");
            img.src = URL.createObjectURL(file);
            img.className = "img-thumbnail";
            img.width = 150;
            img.height = 150;
            previewContainer.appendChild(img);
        } else if (fileType.startsWith("video/")) {
            const video = document.createElement("video");
            video.src = URL.createObjectURL(file);
            video.className = "img-thumbnail";
            video.width = 150;
            video.height = 150;
            video.controls = true;
            previewContainer.appendChild(video);
        }
    }
}
</script>

{% endblock %}