KotoLogProject/KotoLogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from .views import PortfolioView,SearchFormView
from journals.views import HomeView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PortfolioView.as_view(), name="portfolio"),
    path('home/', HomeView.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('journals/', include('journals.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

KotoLogProject/accounts/urls.py
from django.urls import path
from .views import (SignupView, LoginView, LogoutView, UserEditView,UserPageView ,
    CustomPasswordChangeView, CustomPasswordChangeDoneView,
    InvitationUrlView,FamilyDeleteView,ChildDeleteView)

app_name='accounts'
urlpatterns = [
    path('signup/', SignupView.as_view(), name="signup"),
    path('signup/<uuid:uuid>/', SignupView.as_view(), name='signup_with_invite'),
    path('login/', LoginView.as_view(), name="login"),
    path('login/<uuid:uuid>/', LoginView.as_view(), name='login_with_invite'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("user_edit/", UserEditView.as_view(), name="user_edit"),
    path("user_page/", UserPageView.as_view(), name="user_page"),
    path("password_change/", CustomPasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", CustomPasswordChangeDoneView.as_view(), name="password_change_done"),
    path("invitation_url/", InvitationUrlView.as_view(), name="invitation_url"),
    path('family/delete/', FamilyDeleteView.as_view(), name='family_delete'),
    path('child/delete/<int:child_id>/', ChildDeleteView.as_view(), name='child_delete'),
]

KotoLogProject/journals/urls.py
from django.urls import path
from .views import (
    ChildcareJournalListView,CreateChildcareJournalView, 
    ChildcareJournalDetailView,EditChildcareJournalView,
    DeleteChildcareJournalsView)

app_name='journals'
urlpatterns = [
    path("childcare_journal_list/", ChildcareJournalListView.as_view(), name="childcare_journal_list"),
    path('create_childcare_journal/', CreateChildcareJournalView.as_view(), name='create_childcare_journal'),
    path('journal_detail/<int:journal_id>/', ChildcareJournalDetailView.as_view(), name='journal_detail'),
    path('edit_childcare_journal/<int:journal_id>/', EditChildcareJournalView.as_view(), name='edit_childcare_journal'), 
    path('delete_childcare_journals/', DeleteChildcareJournalsView.as_view(), name='delete_childcare_journals'),
]

KotoLogProject/accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm, UserChangeForm, PasswordChangeForm)
from accounts.models import (
    User, Child)
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordChangeForm

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username","account_name","email", 'password1', 'password2']
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
       
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("このメールアドレスは既に登録されています。")
               
        return email
    
    def clean_account_name(self):
        account_name = self.cleaned_data.get('account_name')
                
        if User.objects.filter(account_name=account_name).exists():
            raise forms.ValidationError("このアカウント名は既に登録されています。")
        
        return account_name
        
        
class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField()
    user_cache = None  
    
    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        self.user_cache = authenticate(email=email, password=password) 
        
        if self.user_cache is None:
            raise forms.ValidationError("メールアドレスまたはパスワードが間違っています。")
        
        return self.changed_data

    def get_user(self):
        return self.user_cache
    
class UserEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ["username","account_name","email"]
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        user = self.instance
        
        if User.objects.filter(email=email).exclude(pk=user.pk).exists():
            raise forms.ValidationError("このメールアドレスは既に登録されています。")
               
        return email
    
    def clean_account_name(self):
        account_name = self.cleaned_data.get('account_name')
        user = self.instance       
        if User.objects.filter(account_name=account_name).exclude(pk=user.pk).exists():
            raise forms.ValidationError("このアカウント名は既に登録されています。")
        
        return account_name

class UserPageForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['account_name']

class ChildForm(forms.ModelForm):
    class Meta:
        model = Child
        fields = ['child_name', 'birthday']
        labels = {
            'child_name': '子どもの名前',
            'birthday': '生年月日',
        }
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'}),
        }
        
    def clean(self):
        cleaned_data = super().clean()
        child_name = self.cleaned_data.get('child_name')
        birthday = self.cleaned_data.get('birthday')
        parent = self.instance  #親を取得

        # familyがあるか確認（複数の家族メンバー間での重複チェック）
        family = self.instance.family

        # 同じ名前と生年月日がすでに登録されているか確認
        if Child.objects.filter(child_name=child_name, birthday=birthday, family=family).exists():
            
            raise forms.ValidationError('この名前と生年月日の子どもはすでに登録されています。')

        return cleaned_data

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

KotoLogProject/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from accounts.forms import SignupForm, LoginForm, UserEditForm, UserPageForm, ChildForm,CustomPasswordChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.forms import PasswordChangeForm
from .models import User, Family, Child
from journals.models import ChildcareJournalAccessLog,ChildcareJournal,Favorite
from django.urls import reverse_lazy,reverse
import uuid,json
from django.contrib import messages
from django.db import transaction
from django.db.models import Prefetch, Count, Case, When, Value, BooleanField,Max,OuterRef, Subquery,Q
from django.core.serializers.json import DjangoJSONEncoder

class SignupView(View):

    def get(self, request, uuid=None):
        # UUIDが渡されている場合の家族情報の取得
        family = None
        if uuid:
            families = Family.objects.all()
            
            # invitationsの中から該当するUUIDを探す
            for fam in families:
                for invitation in fam.invitations:
                    if invitation['uuid'] == str(uuid) and not invitation['used']:
                        family = fam
                        break
                    
            if not family:
                messages.error(request, 'この招待URLは無効です。')
                return redirect('home')

        form = SignupForm()
        return render(request, "accounts/signup.html", context={"form": form, "uuid": uuid})

    def post(self, request, uuid=None):
        form = SignupForm(request.POST)
        family = None

        if uuid:
            families = Family.objects.all()
            
            # invitationsの中から該当するUUIDを探す
            for fam in families:
                for invitation in fam.invitations:
                    if invitation['uuid'] == str(uuid) and not invitation['used']:
                        family = fam
                        break
                    
            if not family:
                messages.error(request, 'この招待URLは無効です。')
                return redirect('home')

        if form.is_valid():
            user = form.save(commit=False)

            # UUIDでの家族情報を関連付け
            if family:
                user.family = family
                family.use_invitation(uuid)

            user.save()
            login(request, user)
            messages.success(request, '新規登録が完了しました。')
            return redirect('home')

        return render(request, "accounts/signup.html", context={"form": form})
       
class LoginView(View):
    
    def get(self, request, uuid=None):
        if uuid:
            families = Family.objects.all()
            family = ""
            # invitationsの中から該当するUUIDを探す
            for fam in families:
                for invitation in fam.invitations:
                    if invitation['uuid'] == str(uuid) and not invitation['used']:
                        family = fam
                        break

            if not family:
                messages.error(request, 'この招待URLは無効です。新しい招待URLを発行してください。')
                return redirect('home')

            # 既に家族登録されているユーザーがログインしている場合
            if request.user.is_authenticated:
                if request.user.family:
                    messages.error(request, "既に家族に所属しています。")
                    return redirect('accounts:user_page')

                # 家族登録が未済のログイン済みユーザーを登録
                request.user.family = family
                request.user.save()
                family.use_invitation(uuid)
                messages.success(request, "家族登録が完了しました！")
                return redirect('accounts:user_page')

            # 未ログインユーザーにはメッセージを出してそのままログイン画面表示
            messages.info(request, "家族登録を行うためにログインしてください。")

        return render(request, "accounts/login.html", context={'uuid': uuid})

    def post(self, request, uuid=None):
        form = LoginForm(request.POST)
        
        if form.is_valid():
            user = form.user_cache
            login(request, user)

            # UUIDが存在する場合、家族情報にユーザーを追加
            if uuid:
                families = Family.objects.all()
                
                # invitationsの中から該当するUUIDを探す
                for fam in families:
                    for invitation in fam.invitations:
                        if invitation['uuid'] == str(uuid) and not invitation['used']:
                            family = fam
                            break
                
                if family and user.family is None:
                    user.family = family
                    user.save()
                    family.use_invitation(uuid)
                    messages.success(request, "家族登録が完了しました！")
                    return redirect('accounts:user_page')
                elif family:
                    messages.info(request, "既に家族登録されています。")

            return redirect("home")

        return render(request, "accounts/login.html", context={'form': form})

class LogoutView(LoginRequiredMixin, LogoutView):
     template_name = "common/home.html"

class UserEditView(LoginRequiredMixin, View):
    
    def get(self, request):
        user = request.user
        form = UserEditForm(instance=user)
        password_form = PasswordChangeForm(user=request.user)
        return render(request, 'accounts/user_edit.html', {
            'form': form, 
            'user':user,
            "password_form":password_form
        })

    def post(self, request):
        form = UserEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:user_page")
        return render(request, "accounts/user_edit.html", {"form": form})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['password_change_form'] = PasswordChangeForm(user=self.request.user)
        return context    

class UserPageView(LoginRequiredMixin, View):
    
    def get(self, request):
        user = request.user
        form = UserPageForm(instance=user)

        # 家族が存在する場合は家族情報と子ども情報を取得
        family, family_members, children = self.get_family_info(user)    

        # カレンダー表示用のクエリを発行
        if family:
            records_by_date = ChildcareJournal.objects.filter(
                Q(user__in=family_members) | Q(user=user)).values('published_on').order_by('published_on')
            records_by_date = [
                {
                    'date': record['published_on'].strftime('%Y-%m-%d')
                }
                for record in records_by_date
            ]
        else:
            records_by_date = []

        # 最近見た育児記録の最新のアクセス時間を持つレコードを取得
        latest_recent_journals = (
            ChildcareJournalAccessLog.objects
            .filter(user=user)
            .values('childcare_journal_id')  # 各育児記録ごとにグループ化
            .annotate(latest_accessed=Max('accessed_at'))  # 最新のアクセス時間を取得
        )

        # 最近見た育児記録のクエリセットを生成
        recent_journal_objects = (
            ChildcareJournal.objects
            .filter(id__in=Subquery(latest_recent_journals.values('childcare_journal_id')))  # 最新のアクセスがある育児記録を絞り込み
            .annotate(
                latest_accessed=Subquery(
                    latest_recent_journals.filter(
                        childcare_journal_id=OuterRef('id')
                    ).values('latest_accessed')[:1]  # その育児記録の最新のアクセス日時を取得
                ),
                is_favorited=Case(
                    When(favorite__user=user, then=Value(True)),
                    default=Value(False),
                    output_field=BooleanField()
                )
            )
            .order_by('-latest_accessed')  # 最新のアクセス時間順に並べ替え
            .select_related('child')[:10]  # 必要な関連データを一緒に取得
        )
                
        # ユーザが作成した育児記録を取得
        user_created_journals = ChildcareJournal.objects.filter(user=user).order_by('-published_on').annotate(
            is_favorited=Case(
                When(favorite__user=user, then=Value(True)),
                default=Value(False),
                output_field=BooleanField()
            )
        ).select_related('child')[:10]
        
        child_form = ChildForm()

        # コンテキストに家族情報、子ども情報、フォームを追加
        context = {
            'form': form,
            'user': user,
            'family': family,
            'family_members': family_members,
            'children': children,  
            'child_form': child_form,
            'recent_journal_objects': recent_journal_objects, 
            'user_created_journals': user_created_journals,
            'records_by_date': json.dumps(records_by_date, cls=DjangoJSONEncoder),
        }
        return render(request, "accounts/user_page.html", context)

    
    def post(self, request):
        form = UserPageForm(request.POST, instance=request.user)
        user = request.user
        
        # 子ども追加処理
        if 'add_child' in request.POST:
            child_form = ChildForm(request.POST)
            
            # ユーザーに紐づくFamilyがなければ作成
            if not user.family:
                family = Family.objects.create()
                user.family = family
                user.save()
                        
            if child_form.is_valid():
                child = child_form.save(commit=False)
                child.family = request.user.family
               
                try:
                    child.save()
                    messages.success(request, '子どもが追加されました。')
                    return redirect('accounts:user_page')
                except Exception as e:
                    child_form.add_error(None, 'エラーが発生しました。再度お試しください。')
                                        
            # 家族が存在する場合は家族情報と子ども情報を取得
            family, family_members, children = self.get_family_info(user)
                

KotoLogProject/templates/accounts/invitation_url.html
{% extends 'common/base.html' %}
{% block content %}
<div class="container my-5">
    <h1 class="mb-4">家族招待</h1>
    <div class="alert alert-info">
        <p><strong>利用方法:</strong><br>作成するをクリックし、リンク先URLを表示<br>
        招待したい家族にリンク先を共有しアカウントを登録してもらう<br>
        <small class="text-danger">※発行されたURLは一度利用すると失効します。</small></p>
    </div>
    <div class="text-center my-4">
        <form method="post" action="{% url 'accounts:invitation_url' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-lg">家族招待URLを作成する</button>
        </form>
    </div>
    {% if invitation_url %}
    <div class="form-group text-center my-4">
        <label for="invitation-url" class="form-label">共有リンク:</label>
        <input type="text" class="form-control text-center" id="invitation-url" value="{{ invitation_url }}" readonly>
    </div>
    {% endif %}
    <div class="text-center mt-5">
        <a href="{% url 'accounts:user_page' %}" class="btn btn-link">マイページへ戻る</a>
    </div>
</div>
{% endblock %}

KotoLogProject/templates/accounts/login.html
{% extends 'common/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% if messages %}
                        <div class="alert alert-success">
                            {% for message in messages %}
                            <p>{{ message }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                        <div class="mb-3">
                            <label for="email" class="form-label">メールアドレス</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{ form.email.value|default:'' }}">
                            {{ form.email.errors }}
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">パスワード</label>
                            <input type="password" class="form-control" id="password" name="password" value="{{ form.name.value|default:'' }}">
                            {{ form.password.errors }}
                        </div>
                        <button type="submit" class="btn btn-primary w-100">ログイン</button>
                    </form>
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                    {% endfor%}
                    {% if uuid %}
                    <a href="{% url 'accounts:signup_with_invite' uuid %}" class="btn btn-link">新規登録</a>
                    {% else %}
                    <a href="{% url 'accounts:signup' %}" class="btn btn-link">新規登録</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

KotoLogProject/templates/accounts/password_change.html
{% extends 'common/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="text-center mb-4">パスワード変更</h4>
                    <form method="post" class="needs-validation" novalidate>
                        {% csrf_token %}
                        
                        {% if messages %}
                        <div class="alert alert-success">
                            {% for message in messages %}
                            <p>{{ message }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                        
                        {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <div class="text-danger">{{ field.errors }}</div>
                            {% endif %}
                        </div>
                        {% endfor %}

                        <button type="submit" class="btn btn-primary w-100">パスワード変更</button>
                    </form>

                    <a href="{% url 'accounts:user_page' %}" class="btn btn-link mt-3">アカウント情報画面へ</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

KotoLogProject/templates/accounts/password_change_done.html
{% extends "common/base.html" %}

{% block title %}パスワード変更完了{% endblock %}

{% block content %}
<section class="password-change-complete text-center">
    <h1>パスワード変更完了</h1>
    <p class="mb-4">パスワードを変更しました。</p>
    <a class="btn btn-secondary" href="{% url 'accounts:user_page' %}">アカウント情報画面へ</a>
</section>
{% endblock %}

KotoLogProject/templates/accounts/user_edit.html
{% extends 'common/base.html' %}
{% block content %}
<section class="signup container my-5 p-4 shadow-sm rounded bg-white">
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        {{ form.errors }}
        
        <div class="mb-3">
            <label for="username" class="form-label">名前</label>
            <input type="text" name="username" id="username" value="{{ form.username.value|default:'' }}" class="form-control" required>
            <small class="form-text text-muted">※名前は公開されません。</small>
            {{ form.username.errors }}
        </div>

        <div class="mb-3">
            <label for="account_name" class="form-label">アカウント名<span class="text-muted"> (半角英数字のみ)</span></label>
            <input type="text" name="account_name" id="account_name" value="{{ form.account_name.value|default:'' }}" class="form-control" required>
            <small class="form-text text-muted">※アカウント名は育児記録を「全体に公開」に設定した場合に表示されます。</small>
            {{ form.account_name.errors }}
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">メールアドレス</label>
            <input type="email" name="email" id="email" value="{{ form.email.value|default:'' }}" class="form-control" required>
            {{ form.email.errors }}
        </div>
        <button type="submit" class="btn btn-primary w-100">変更</button>
        <a href="{% url "accounts:password_change" %}" class="btn btn-link">パスワード変更</a>
    </form>
</section>
<script>
    $(document).ready(function() {
        $('#account_name').on('input', function() {
            const inputValue = $(this).val();
            if (!inputValue.startsWith('@')) {
                $(this).val(`@${inputValue}`);
            }
        });
    });
</script>
{% endblock %}

KotoLogProject/templates/accounts/user_page.html
{% extends 'common/base.html' %}
{% block content %}
{% load static %}
    {% if messages %}
      <div class="alert alert-success">
          {% for message in messages %}
              <p>{{ message }}</p>
          {% endfor %}
      </div>
    {% endif %}
<section id="userpage" class="d-flex flex-column flex-md-row">
<aside id="user_info" class="user-info">
        <h2>
            <a href="{% url 'accounts:user_edit' %}">{{ user.account_name }}
                <img src="{% static 'img/user_edit.png' %}" alt="Edit">
            </a>
        </h2>

        <!-- Family Information Section -->
        <h2 data-bs-toggle="collapse" data-bs-target="#familyInfo" aria-expanded="true" aria-controls="familyInfo" class="info-title">
            家族情報
        </h2>
        <div id="familyInfo" class="collapse show">
        <ul class="user-info-list">
        {% for member in family_members %}
            <li class="user-info-item">
            {{ member.username }} / {{ member.account_name }}
            <form method="post" action="{% url 'accounts:family_delete' %}" onsubmit="return confirmDelete('{{ member.username }}')">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">削除</button>
            </form>
            </li>
        {% empty %}
            <li>家族情報が登録されていません。</li>
        {% endfor %}
            </ul>
            <a href="{% url 'accounts:invitation_url' %}">家族招待URLを発行</a>
        </div>

        <!-- Child Information Section -->
        <h2 data-bs-toggle="collapse" data-bs-target="#childInfo" aria-expanded="true" aria-controls="childInfo" class="info-title">
            子ども情報
        </h2>
        <div id="childInfo" class="collapse show">
        <ul class="user-info-list">
        {% for child in children %}
            <li class="user-info-item">
            {{ child.child_name }} / {{ child.birthday }}
            <form method="post" action="{% url 'accounts:child_delete' child.id %}" onsubmit="return confirmDelete('{{ child.child_name }}')">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">削除</button>
            </form>
            </li>
        {% empty %}
            <li>子ども情報が登録されていません。</li>
        {% endfor %}
            </ul>
            <button type="button" data-bs-toggle="modal" data-bs-target="#addChildModal">子どもを追加する</button>
        </div>
    </aside>
    <section id="account_journals" class="content-section">
        <div id="calendar" class="calendar mb-4"></div>
        <article>
            <h2 class="journal_title">最近見た育児記録</h2>
            <div id="recentedCarousel" class="carousel-container mb-4">
                <button class="carousel-prev" data-target="#recentedCarousel">＜</button>
                <div class="carousel-track-container">
                    <div class="carousel-track">
                        {% for journal in recent_journal_objects %}
                            {% include 'journals/childcare_journal_card.html' %}
                        {% empty%}
                        <p>最近見た育児記録はありません。</p>
                        {% endfor %}
                    </div>
                </div>
                <button class="carousel-next" data-target="#recentedCarousel">＞</button>
            </div>  
        </article>
        <article>
            <h2 class="journal_title">作成した育児記録</h2>
                <div id="createdCarousel" class="carousel-container mb-4">
                    <button class="carousel-prev" data-target="#createdCarousel">＜</button>
                    <div class="carousel-track-container">
                        <div class="carousel-track">
                            {% for journal in user_created_journals %}
                                {% include 'journals/childcare_journal_card.html' %}
                            {% empty%}
                            <p>最近作成した育児記録はありません。</p>  
                            {% endfor %}
                        </div>
                    </div>
                    <button class="carousel-next" data-target="#createdCarousel">＞</button>
                </div>      
        </article>
  </section>    
</section>


  <!-- 詳細表示モーダルテンプレートの読み込み -->
    {% include 'journals/journal_detail.html' %}

<!-- 子ども追加モーダルウィンドウ -->
<div class="modal fade" id="addChildModal" tabindex="-1" aria-labelledby="addChildModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addChildModalLabel">子どもを追加する</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST">
          {% csrf_token %}
          {{ child_form.as_p }}
          <button type="submit" name="add_child" class="btn btn-primary">追加</button>
        </form>
      </div>
    </div>
  </div>
</div>
<script>
document.addEventListener('DOMContentLoaded', function() {
    const calendarEl = document.getElementById('calendar');
    const recordsByDate = JSON.parse('{{ records_by_date|escapejs }}');  // DjangoテンプレートからJSONを取得
    
    const datesWithRecords = recordsByDate.map(record => record.date);  // 育児記録がある日付のリスト

    const calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth',  // 月表示
        locale: 'ja',  // 日本語化
        headerToolbar: {
            left: 'prev',  // 前月ボタン
            center: 'title',  // タイトル（年・月）
            right: 'next'  // 次月ボタン
        },
        eventContent: false,
        dayCellContent: function(info) {
            // ローカルタイムで日付を取得
            const year = info.date.getFullYear();
            const month = String(info.date.getMonth() + 1).padStart(2, '0');  // 月は0から始まるため+1
            const day = String(info.date.getDate()).padStart(2, '0');
            const dateStr = `${year}-${month}-${day}`;  // YYYY-MM-DD形式
            

            // 育児記録がある場合
            if (datesWithRecords.includes(dateStr)) {

                const record = recordsByDate.find(r => r.date === dateStr);
                return { html: `<a href="{% url 'journals:childcare_journal_list' %}?date=${record.date}">${info.date.getDate()}</a>` };
            }

            // 通常の日付（黒文字表示）
           return { html: `<div style="text-align: center;">${info.date.getDate()}</div>` };
        },
        height:400
    });

    $('.fc-daygrid-day-events').hide();

    calendar.render();
});

    // 削除確認メッセージを表示する
    function confirmDelete(item) {
        return confirm(item + 'を本当に削除しますか？');
    }
</script>
{% load static %}
<script src="{% static 'js/function.js' %}"></script>     
{% endblock %}